# Generated by Django 5.0.6 on 2024-07-15 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50, verbose_name='Bouquet Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('is_active', models.BooleanField(default=True)),
                ('fimage', models.ImageField(upload_to='image')),
                ('cat', models.IntegerField(choices=[(1, 'RedRose'), (2, 'YelloRose'), (3, 'WhiteRose'), (4, 'PinkRose'), (5, 'Flower'), (6, 'Combos'), (7, 'Birthday'), (8, 'Anniversary'), (9, 'Plants'), (10, 'Personalised'), (11, 'Occasions'), (12, 'Chocolate_Bouquet'), (13, 'Special')], verbose_name='Category')),
                ('flowert', models.CharField(max_length=70, verbose_name='Flower Type')),
                ('nos', models.IntegerField(verbose_name='No. Of Stems')),
                ('flowc', models.CharField(max_length=100, verbose_name='Flower Contains')),
                ('packing', models.CharField(max_length=70, verbose_name='Packing')),
                ('packingc', models.CharField(max_length=70, verbose_name='Packing Color')),
                ('ribb', models.CharField(max_length=70, verbose_name='Ribbons')),
                ('np', models.CharField(max_length=70, verbose_name='No. Of Packing')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='app.flower')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=1)),
                ('amt', models.IntegerField()),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='app.flower')),
                ('uid', models.ForeignKey(db_column='uid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
