# Generated by Django 5.0.6 on 2024-07-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_create_udetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='udetail',
            name='uname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
